import { Group, GroupDetail } from '@services/api/types'

export const MOCK_GROUPS: Group[] = [
  {
    id: 1,
    name: '달봉이네 가족',
    introduction: '우리는 달봉이',
    imageUrl: null,
    isPublic: true,
    likeCount: 17589,
    badgeCount: 1,
    postCount: 1,
    createdAt: '2024-01-22T07:47:49.803Z',
  },
  {
    id: 2,
    name: '그룹2',
    introduction: '그룹2 소개',
    imageUrl: '/images/image-example.png',
    isPublic: true,
    likeCount: 3,
    badgeCount: 3,
    postCount: 3,
    createdAt: '2024-02-22T07:47:49.803Z',
  },
  {
    id: 3,
    name: '그룹3',
    introduction: '그룹3 소개',
    imageUrl: null,
    isPublic: true,
    likeCount: 2,
    badgeCount: 2,
    postCount: 2,
    createdAt: '2024-03-03T07:47:49.803Z',
  },
  {
    id: 4,
    name: '달봉이네 가족',
    introduction: '우리는 달봉이',
    imageUrl: '/images/image-example.png',
    isPublic: true,
    likeCount: 17589,
    badgeCount: 1,
    postCount: 1,
    createdAt: '2024-01-22T07:47:49.803Z',
  },
  {
    id: 5,
    name: '그룹2',
    introduction: '그룹2 소개',
    imageUrl: '/images/image-example.png',
    isPublic: true,
    likeCount: 3,
    badgeCount: 3,
    postCount: 3,
    createdAt: '2024-02-22T07:47:49.803Z',
  },
  {
    id: 6,
    name: '그룹3',
    introduction: '그룹3 소개',
    imageUrl: '/images/image-example.png',
    isPublic: true,
    likeCount: 2,
    badgeCount: 2,
    postCount: 2,
    createdAt: '2024-03-03T07:47:49.803Z',
  },
]

export const MOCK_PRIVATE_GROUPS: Group[] = [
  {
    id: 4,
    name: '비공개 그룹1',
    introduction: null,
    imageUrl: null,
    isPublic: false,
    likeCount: 4,
    badgeCount: null,
    postCount: 4,
    createdAt: '2024-02-22T07:47:49.803Z',
  },
  {
    id: 5,
    name: '비공개 그룹2',
    introduction: null,
    imageUrl: null,
    isPublic: false,
    likeCount: 5,
    badgeCount: null,
    postCount: 5,
    createdAt: '2024-02-22T07:47:49.803Z',
  },
  {
    id: 6,
    name: '비공개 그룹3',
    introduction: null,
    imageUrl: null,
    isPublic: false,
    likeCount: 6,
    badgeCount: null,
    postCount: 6,
    createdAt: '2024-02-22T07:47:49.803Z',
  }, {
    id: 7,
    name: '비공개 그룹1',
    introduction: null,
    imageUrl: null,
    isPublic: false,
    likeCount: 4,
    badgeCount: null,
    postCount: 4,
    createdAt: '2024-02-22T07:47:49.803Z',
  },
  {
    id: 8,
    name: '비공개 그룹2',
    introduction: null,
    imageUrl: null,
    isPublic: false,
    likeCount: 5,
    badgeCount: null,
    postCount: 5,
    createdAt: '2024-02-22T07:47:49.803Z',
  },
  {
    id: 9,
    name: '비공개 그룹3',
    introduction: null,
    imageUrl: null,
    isPublic: false,
    likeCount: 6,
    badgeCount: null,
    postCount: 6,
    createdAt: '2024-02-22T07:47:49.803Z',
  }, {
    id: 10,
    name: '비공개 그룹1',
    introduction: null,
    imageUrl: null,
    isPublic: false,
    likeCount: 4,
    badgeCount: null,
    postCount: 4,
    createdAt: '2024-02-22T07:47:49.803Z',
  },
  {
    id: 11,
    name: '비공개 그룹2',
    introduction: null,
    imageUrl: null,
    isPublic: false,
    likeCount: 5,
    badgeCount: null,
    postCount: 5,
    createdAt: '2024-02-22T07:47:49.803Z',
  },
  {
    id: 12,
    name: '비공개 그룹3',
    introduction: null,
    imageUrl: null,
    isPublic: false,
    likeCount: 6,
    badgeCount: null,
    postCount: 6,
    createdAt: '2024-02-22T07:47:49.803Z',
  },
]

export const MOCK_GROUP_DETAIL: GroupDetail = {
  id: 1,
  name: '인천 앞바다에서 무려 60cm 월척을 낚다!',
  imageUrl: '/images/image-example.png',
  isPublic: true,
  likeCount: 17589,
  badges: ['badge1', 'badge2', 'badge3'],
  postCount: 1,
  createdAt: '2024-03-02T07:47:49.803Z',
  introduction: '인천 앞바다에서 월척을 낚았습니다!',
}
